time_zone: "Hanoi"
password:
  min_character: 8
exams:
  status:
    "unstart": 0
    "started": 1
    "inprogress": 2
    "uncheck": 3
    "checked": 4
users:
  action:
    login: 0
    logout: 1
view_limit_activities: 15
answers_count_min: 1
per_page_activity: 15
time_to_notice_start_exam: 8
