password:
  min_character: 8
exams:
  status:
    "unstart": 0
    "started": 1
    "inprogress": 2
    "uncheck": 3
    "checked": 4
users:
  action:
    login: 0
    logout: 1
view_limit_activities: 15
